### ISSUE TITLE
Created HTML does not show map-tiles with Chrome or Edge

### ISSUE THREAD

**Issue by jibaer-izw** [jwass/mplleaflet#81]
I have created a map of a GPS-track. If i open the HTML-File with Chrome (99.0.4844.51) or Edge ( 99.0.1150.39) i only see my track on a blank area without the tile-data. With Firefox the map is displayed.

**Comment by srcatto** [comment]
A course I mentor also has a student posting about this. Inspect / Console logs.

(a) Chrome, right click the map area, Inspect, Console (script error messages)
Error - Mixed Content: The page at `'<URL>'` was loaded over HTTPS, but requested an insecure image `'<URL>'`. This content should also be served over HTTPS.
... requested an insecure image 'http://b.tile.openstreetmap.org/9/136/189.png'. This content should also be served over HTTPS.

Chrome then tries to load the map using https, and it fails.
190.png:1          GET https://c.tile.openstreetmap.org/9/136/190.png 403 (Forbidden)
I'm using Google Chrome Version 99.0.4844.74 (Official Build) (64-bit) on Win 11 Pro x64 21H2 up to date.

(b) Firefox
Warning - Loading mixed (insecure) display content "http://b.tile.openstreetmap.org/9/138/190.png" on a secure page
While Firefox loads ok,
GET https://b.tile.openstreetmap.org/9/136/189.png
Firefox 98.0.1 (64-bit)

**Comment by jibaer-izw** [comment]
Problem fixed with patching 'mplleaflet\maptiles.py': Changing http:// to https://

**Comment by srcatto** [comment]
That is not something we can ask students to do, especially since they don't have permission in to /opt. The software environment is 3+ years old & cloned for each new student. We might be able to update packages if there are no compatibility problems. Currently using Python 3.6.2 & mplleaflet==0.0.5. Editing the source locally doesn't fix the issue. It is an issue with the built-in URLs when installed.

**Comment by jibaer-izw** [comment]
The problem is that the maintainer of the package seems to be no longer active. All pull-requests are not processed and the version on PyPi is from 2015. I have send an e-mail to the maintainer and asked about further support. See what happens

**Comment by srcatto** [comment]
Thank you.
